import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import '../../styles/header.css'
import Link from "next/link"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const pages = {
  home: "/",
  about: "/about",
  contacts: "/contacts",
  products: "/our-products",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>

          {Object.entries(pages).map(([name, path]) => (
            <li key={name}>
              <Link href={path}>{name}</Link>
            </li>
          ))}
        </nav>
        {children}
      </body>
    </html>
  )
}
